version: "3.7"

services:
  web:
    restart: always
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - NEXT_SITE_NAME=${NEXT_SITE_NAME}
      - NEXT_SITE_EMAIL=${NEXT_SITE_EMAIL}
      - RESEND_API_KEY=124
#      - RESEND_API_KEY=${RESEND_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=boilerplate
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
    driver: local
