import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { NextSessionProvider } from "@/components/NextSessionProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS Boilerplate",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
    <body className={inter.className}>
    <NextSessionProvider session={session}>
      <Header />
      <div className="container py-8">
        {children}
      </div>
      {/*<Footer />*/}
    </NextSessionProvider>
    </body>
    </html>
  );
}
